region             = "ap-south-1"
profile            = ""
vpc_name           = ""
vpc_cidr_block     = ""
ig                 = "ig"
subnet_names       = []
subnet_cidr_blocks = []
availability_zones = []
public_subnet_name = ""
public_subnet_cidr_block = "10.0.8.0/24"
public_subnet_availability_zone ="ap-south-1a"